### ISSUE TITLE
Typo: wrong version number of Geolib+ after installation

### ISSUE THREAD

**Issue by martijnkriebel** [Deltares/geolib-plus#2]
The most recent version of Geolib+ is v0.1.1. But when I look in the installation environment it tells me I have v0.1.2 installed. This occurs both while using requirements.txt and Poetry pyproject.toml for installation.

I could only trace this back to the pyproject.toml file, which states `version = "0.1.2"`. However, I'm not sure whether this is also the source of the typo when installing from the requirements.txt file or if there is another typo in another file that causes this.

**Comment by evetion** [comment]
The most recent released version was 0.1.1, but the development version, as in master, was 0.1.2. This was an unreleased version however.

The pyproject.toml does indeed define the version.

In the meantime, I've released 0.1.2, as indicated by the GitHub release, git tag and PyPi release.

In the future you might see 0.1.3 if you install from git, but you should consider this a prerelease version.
