### ISSUE TITLE
Strict package requirements (e.g. shapely)

### ISSUE THREAD

**Issue by chrispijo** [Deltares/geolib-plus#20]
I wanted to ask why the package requirements of geolib-plus are so strict. We regularly come across the issue below. It forces us to stay with shapely==2.0.0, even though shapely has already done improvents in newer versions (e.g. they are now at 2.0.1). Similar situation can occur for other packages like pandas. 

Would it be possible that geolib-plus can set its requirements to an `equal to or larger then` (shapely>=2.0.0)?

```
The conflict is caused by:
    d-geolib-plus 0.2.1 depends on shapely==2.0.0
```

**Comment by EleniSmyrniou** [comment]
Thanks for the suggestion! You are right there should be no reason why the requirements are so strict. I will make an issue about that. You can update the code if you want by yourself and make a pull request or I will change that later this month.
