### ISSUE TITLE
Probabilistic macrostability

### ISSUE THREAD

**Issue by ElhMah** [Deltares/GEOLib-Plus#23]
### Adding the following Macrostability Jupyter notebooks:

@EleniSmyrniou Would you please do it?

[Tutorial 1 - Fit Lognormal Distribution](https://deltares-my.sharepoint.com/:u:/r/personal/ana_martinsteixeira_deltares_nl/Documents/Documents/2023%20projects/11209051%20AS%20DIV/SP5%20Handreiking/Handreiking%20Faalkans%20Analyse/Tutorials/Tutorial%201%20-%20Fit%20Lognormal%20Distribution.ipynb?csf=1&web=1&e=FfVrnm)

[Tutorial 2 - Fit GEV Distribution](https://deltares-my.sharepoint.com/:u:/r/personal/ana_martinsteixeira_deltares_nl/Documents/Documents/2023%20projects/11209051%20AS%20DIV/SP5%20Handreiking/Handreiking%20Faalkans%20Analyse/Tutorials/Tutorial%202%20-%20Fit%20GEV%20Distribution.ipynb?csf=1&web=1&e=8CMJRo)

[Tutorial 3 - Fragility curve Integration](https://deltares-my.sharepoint.com/:u:/r/personal/ana_martinsteixeira_deltares_nl/Documents/Documents/2023%20projects/11209051%20AS%20DIV/SP5%20Handreiking/Handreiking%20Faalkans%20Analyse/Tutorials/Tutorial%203%20-%20Fragility%20Curve%20Integration.ipynb?csf=1&web=1&e=SJkDay)

[Tutorial 4 - Combine 2 Fragility Curves Uplift Scenario Probability](https://deltares-my.sharepoint.com/:u:/r/personal/ana_martinsteixeira_deltares_nl/Documents/Documents/2023%20projects/11209051%20AS%20DIV/SP5%20Handreiking/Handreiking%20Faalkans%20Analyse/Tutorials/Tutorial%204%20-%20Combine%202%20Fragility%20Curves%20Uplift%20Scenario%20Probability.ipynb?csf=1&web=1&e=UzpKri)

**Comment by markvanderkrogt** [comment]
@EleniSmyrniou @ElhMah please make sure we also commit the necessary data files (txt and json)
